/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepositarRouteImport } from './routes/_authenticated/depositar'
import { Route as AuthenticatedIndicacoesRouteImport } from './routes/_authenticated/indicacoes'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPontosRouteImport } from './routes/_authenticated/pontos'
import { Route as AuthenticatedSaquesRouteImport } from './routes/_authenticated/saques'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminGatewaysRouteImport } from './routes/_authenticated/admin/gateways'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin/pagamentos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminPlanosRouteImport } from './routes/_authenticated/admin/planos'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'
import { Route as AuthenticatedAdminSaquesRouteImport } from './routes/_authenticated/admin/saques'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedDepositoDepositIdRouteImport } from './routes/_authenticated/deposito.$depositId'
import { Route as AuthenticatedPagamentoPaymentIdRouteImport } from './routes/_authenticated/pagamento.$paymentId'
import { Route as ApiPublicCronRoiRouteImport } from './routes/api/public/cron/roi'
import { Route as ApiPublicWebhooksPixRouteImport } from './routes/api/public/webhooks/pix'
import { Route as ApiPublicWebhooksConnectpayCashoutRouteImport } from './routes/api/public/webhooks/connectpay/cashout'
import { Route as ApiPublicWebhooksConnectpayCryptoRouteImport } from './routes/api/public/webhooks/connectpay/crypto'
import { Route as ApiPublicWebhooksConnectpayPixRouteImport } from './routes/api/public/webhooks/connectpay/pix'
import { Route as ApiPublicWebhooksNowpaymentsPaymentRouteImport } from './routes/api/public/webhooks/nowpayments/payment'
import { Route as ApiPublicWebhooksNowpaymentsPayoutRouteImport } from './routes/api/public/webhooks/nowpayments/payout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositarRoute = AuthenticatedDepositarRouteImport.update({
  id: '/depositar',
  path: '/depositar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicacoesRoute = AuthenticatedIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPontosRoute = AuthenticatedPontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaquesRoute = AuthenticatedSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/admin/banners',
    path: '/admin/banners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGatewaysRoute =
  AuthenticatedAdminGatewaysRouteImport.update({
    id: '/admin/gateways',
    path: '/admin/gateways',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/admin/pagamentos',
    path: '/admin/pagamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlanosRoute =
  AuthenticatedAdminPlanosRouteImport.update({
    id: '/admin/planos',
    path: '/admin/planos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSaquesRoute =
  AuthenticatedAdminSaquesRouteImport.update({
    id: '/admin/saques',
    path: '/admin/saques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositoDepositIdRoute =
  AuthenticatedDepositoDepositIdRouteImport.update({
    id: '/deposito/$depositId',
    path: '/deposito/$depositId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagamentoPaymentIdRoute =
  AuthenticatedPagamentoPaymentIdRouteImport.update({
    id: '/pagamento/$paymentId',
    path: '/pagamento/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronRoiRoute = ApiPublicCronRoiRouteImport.update({
  id: '/api/public/cron/roi',
  path: '/api/public/cron/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPixRoute = ApiPublicWebhooksPixRouteImport.update({
  id: '/api/public/webhooks/pix',
  path: '/api/public/webhooks/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksConnectpayCashoutRoute =
  ApiPublicWebhooksConnectpayCashoutRouteImport.update({
    id: '/api/public/webhooks/connectpay/cashout',
    path: '/api/public/webhooks/connectpay/cashout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksConnectpayCryptoRoute =
  ApiPublicWebhooksConnectpayCryptoRouteImport.update({
    id: '/api/public/webhooks/connectpay/crypto',
    path: '/api/public/webhooks/connectpay/crypto',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksConnectpayPixRoute =
  ApiPublicWebhooksConnectpayPixRouteImport.update({
    id: '/api/public/webhooks/connectpay/pix',
    path: '/api/public/webhooks/connectpay/pix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNowpaymentsPaymentRoute =
  ApiPublicWebhooksNowpaymentsPaymentRouteImport.update({
    id: '/api/public/webhooks/nowpayments/payment',
    path: '/api/public/webhooks/nowpayments/payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNowpaymentsPayoutRoute =
  ApiPublicWebhooksNowpaymentsPayoutRouteImport.update({
    id: '/api/public/webhooks/nowpayments/payout',
    path: '/api/public/webhooks/nowpayments/payout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depositar': typeof AuthenticatedDepositarRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/pontos': typeof AuthenticatedPontosRoute
  '/saques': typeof AuthenticatedSaquesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/deposito/$depositId': typeof AuthenticatedDepositoDepositIdRoute
  '/pagamento/$paymentId': typeof AuthenticatedPagamentoPaymentIdRoute
  '/api/public/cron/roi': typeof ApiPublicCronRoiRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
  '/api/public/webhooks/connectpay/cashout': typeof ApiPublicWebhooksConnectpayCashoutRoute
  '/api/public/webhooks/connectpay/crypto': typeof ApiPublicWebhooksConnectpayCryptoRoute
  '/api/public/webhooks/connectpay/pix': typeof ApiPublicWebhooksConnectpayPixRoute
  '/api/public/webhooks/nowpayments/payment': typeof ApiPublicWebhooksNowpaymentsPaymentRoute
  '/api/public/webhooks/nowpayments/payout': typeof ApiPublicWebhooksNowpaymentsPayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depositar': typeof AuthenticatedDepositarRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/pontos': typeof AuthenticatedPontosRoute
  '/saques': typeof AuthenticatedSaquesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/deposito/$depositId': typeof AuthenticatedDepositoDepositIdRoute
  '/pagamento/$paymentId': typeof AuthenticatedPagamentoPaymentIdRoute
  '/api/public/cron/roi': typeof ApiPublicCronRoiRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
  '/api/public/webhooks/connectpay/cashout': typeof ApiPublicWebhooksConnectpayCashoutRoute
  '/api/public/webhooks/connectpay/crypto': typeof ApiPublicWebhooksConnectpayCryptoRoute
  '/api/public/webhooks/connectpay/pix': typeof ApiPublicWebhooksConnectpayPixRoute
  '/api/public/webhooks/nowpayments/payment': typeof ApiPublicWebhooksNowpaymentsPaymentRoute
  '/api/public/webhooks/nowpayments/payout': typeof ApiPublicWebhooksNowpaymentsPayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/depositar': typeof AuthenticatedDepositarRoute
  '/_authenticated/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/pontos': typeof AuthenticatedPontosRoute
  '/_authenticated/saques': typeof AuthenticatedSaquesRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/deposito/$depositId': typeof AuthenticatedDepositoDepositIdRoute
  '/_authenticated/pagamento/$paymentId': typeof AuthenticatedPagamentoPaymentIdRoute
  '/api/public/cron/roi': typeof ApiPublicCronRoiRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
  '/api/public/webhooks/connectpay/cashout': typeof ApiPublicWebhooksConnectpayCashoutRoute
  '/api/public/webhooks/connectpay/crypto': typeof ApiPublicWebhooksConnectpayCryptoRoute
  '/api/public/webhooks/connectpay/pix': typeof ApiPublicWebhooksConnectpayPixRoute
  '/api/public/webhooks/nowpayments/payment': typeof ApiPublicWebhooksNowpaymentsPaymentRoute
  '/api/public/webhooks/nowpayments/payout': typeof ApiPublicWebhooksNowpaymentsPayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/carteira'
    | '/conta'
    | '/dashboard'
    | '/depositar'
    | '/indicacoes'
    | '/loja'
    | '/notificacoes'
    | '/pedidos'
    | '/planos'
    | '/pontos'
    | '/saques'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/gateways'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/planos'
    | '/admin/produtos'
    | '/admin/saques'
    | '/admin/usuarios'
    | '/deposito/$depositId'
    | '/pagamento/$paymentId'
    | '/api/public/cron/roi'
    | '/api/public/webhooks/pix'
    | '/api/public/webhooks/connectpay/cashout'
    | '/api/public/webhooks/connectpay/crypto'
    | '/api/public/webhooks/connectpay/pix'
    | '/api/public/webhooks/nowpayments/payment'
    | '/api/public/webhooks/nowpayments/payout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/carteira'
    | '/conta'
    | '/dashboard'
    | '/depositar'
    | '/indicacoes'
    | '/loja'
    | '/notificacoes'
    | '/pedidos'
    | '/planos'
    | '/pontos'
    | '/saques'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/gateways'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/planos'
    | '/admin/produtos'
    | '/admin/saques'
    | '/admin/usuarios'
    | '/deposito/$depositId'
    | '/pagamento/$paymentId'
    | '/api/public/cron/roi'
    | '/api/public/webhooks/pix'
    | '/api/public/webhooks/connectpay/cashout'
    | '/api/public/webhooks/connectpay/crypto'
    | '/api/public/webhooks/connectpay/pix'
    | '/api/public/webhooks/nowpayments/payment'
    | '/api/public/webhooks/nowpayments/payout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/_authenticated/carteira'
    | '/_authenticated/conta'
    | '/_authenticated/dashboard'
    | '/_authenticated/depositar'
    | '/_authenticated/indicacoes'
    | '/_authenticated/loja'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pedidos'
    | '/_authenticated/planos'
    | '/_authenticated/pontos'
    | '/_authenticated/saques'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/gateways'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/planos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/saques'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/deposito/$depositId'
    | '/_authenticated/pagamento/$paymentId'
    | '/api/public/cron/roi'
    | '/api/public/webhooks/pix'
    | '/api/public/webhooks/connectpay/cashout'
    | '/api/public/webhooks/connectpay/crypto'
    | '/api/public/webhooks/connectpay/pix'
    | '/api/public/webhooks/nowpayments/payment'
    | '/api/public/webhooks/nowpayments/payout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  ApiPublicCronRoiRoute: typeof ApiPublicCronRoiRoute
  ApiPublicWebhooksPixRoute: typeof ApiPublicWebhooksPixRoute
  ApiPublicWebhooksConnectpayCashoutRoute: typeof ApiPublicWebhooksConnectpayCashoutRoute
  ApiPublicWebhooksConnectpayCryptoRoute: typeof ApiPublicWebhooksConnectpayCryptoRoute
  ApiPublicWebhooksConnectpayPixRoute: typeof ApiPublicWebhooksConnectpayPixRoute
  ApiPublicWebhooksNowpaymentsPaymentRoute: typeof ApiPublicWebhooksNowpaymentsPaymentRoute
  ApiPublicWebhooksNowpaymentsPayoutRoute: typeof ApiPublicWebhooksNowpaymentsPayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depositar': {
      id: '/_authenticated/depositar'
      path: '/depositar'
      fullPath: '/depositar'
      preLoaderRoute: typeof AuthenticatedDepositarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicacoes': {
      id: '/_authenticated/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AuthenticatedIndicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pontos': {
      id: '/_authenticated/pontos'
      path: '/pontos'
      fullPath: '/pontos'
      preLoaderRoute: typeof AuthenticatedPontosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saques': {
      id: '/_authenticated/saques'
      path: '/saques'
      fullPath: '/saques'
      preLoaderRoute: typeof AuthenticatedSaquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gateways': {
      id: '/_authenticated/admin/gateways'
      path: '/admin/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AuthenticatedAdminGatewaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/admin/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/planos': {
      id: '/_authenticated/admin/planos'
      path: '/admin/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AuthenticatedAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/saques': {
      id: '/_authenticated/admin/saques'
      path: '/admin/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof AuthenticatedAdminSaquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposito/$depositId': {
      id: '/_authenticated/deposito/$depositId'
      path: '/deposito/$depositId'
      fullPath: '/deposito/$depositId'
      preLoaderRoute: typeof AuthenticatedDepositoDepositIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamento/$paymentId': {
      id: '/_authenticated/pagamento/$paymentId'
      path: '/pagamento/$paymentId'
      fullPath: '/pagamento/$paymentId'
      preLoaderRoute: typeof AuthenticatedPagamentoPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/roi': {
      id: '/api/public/cron/roi'
      path: '/api/public/cron/roi'
      fullPath: '/api/public/cron/roi'
      preLoaderRoute: typeof ApiPublicCronRoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/pix': {
      id: '/api/public/webhooks/pix'
      path: '/api/public/webhooks/pix'
      fullPath: '/api/public/webhooks/pix'
      preLoaderRoute: typeof ApiPublicWebhooksPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/connectpay/cashout': {
      id: '/api/public/webhooks/connectpay/cashout'
      path: '/api/public/webhooks/connectpay/cashout'
      fullPath: '/api/public/webhooks/connectpay/cashout'
      preLoaderRoute: typeof ApiPublicWebhooksConnectpayCashoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/connectpay/crypto': {
      id: '/api/public/webhooks/connectpay/crypto'
      path: '/api/public/webhooks/connectpay/crypto'
      fullPath: '/api/public/webhooks/connectpay/crypto'
      preLoaderRoute: typeof ApiPublicWebhooksConnectpayCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/connectpay/pix': {
      id: '/api/public/webhooks/connectpay/pix'
      path: '/api/public/webhooks/connectpay/pix'
      fullPath: '/api/public/webhooks/connectpay/pix'
      preLoaderRoute: typeof ApiPublicWebhooksConnectpayPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/nowpayments/payment': {
      id: '/api/public/webhooks/nowpayments/payment'
      path: '/api/public/webhooks/nowpayments/payment'
      fullPath: '/api/public/webhooks/nowpayments/payment'
      preLoaderRoute: typeof ApiPublicWebhooksNowpaymentsPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/nowpayments/payout': {
      id: '/api/public/webhooks/nowpayments/payout'
      path: '/api/public/webhooks/nowpayments/payout'
      fullPath: '/api/public/webhooks/nowpayments/payout'
      preLoaderRoute: typeof ApiPublicWebhooksNowpaymentsPayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositarRoute: typeof AuthenticatedDepositarRoute
  AuthenticatedIndicacoesRoute: typeof AuthenticatedIndicacoesRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPontosRoute: typeof AuthenticatedPontosRoute
  AuthenticatedSaquesRoute: typeof AuthenticatedSaquesRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminGatewaysRoute: typeof AuthenticatedAdminGatewaysRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminPlanosRoute: typeof AuthenticatedAdminPlanosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminSaquesRoute: typeof AuthenticatedAdminSaquesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedDepositoDepositIdRoute: typeof AuthenticatedDepositoDepositIdRoute
  AuthenticatedPagamentoPaymentIdRoute: typeof AuthenticatedPagamentoPaymentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositarRoute: AuthenticatedDepositarRoute,
  AuthenticatedIndicacoesRoute: AuthenticatedIndicacoesRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPontosRoute: AuthenticatedPontosRoute,
  AuthenticatedSaquesRoute: AuthenticatedSaquesRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminGatewaysRoute: AuthenticatedAdminGatewaysRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminPlanosRoute: AuthenticatedAdminPlanosRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
  AuthenticatedAdminSaquesRoute: AuthenticatedAdminSaquesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedDepositoDepositIdRoute: AuthenticatedDepositoDepositIdRoute,
  AuthenticatedPagamentoPaymentIdRoute: AuthenticatedPagamentoPaymentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  ApiPublicCronRoiRoute: ApiPublicCronRoiRoute,
  ApiPublicWebhooksPixRoute: ApiPublicWebhooksPixRoute,
  ApiPublicWebhooksConnectpayCashoutRoute:
    ApiPublicWebhooksConnectpayCashoutRoute,
  ApiPublicWebhooksConnectpayCryptoRoute:
    ApiPublicWebhooksConnectpayCryptoRoute,
  ApiPublicWebhooksConnectpayPixRoute: ApiPublicWebhooksConnectpayPixRoute,
  ApiPublicWebhooksNowpaymentsPaymentRoute:
    ApiPublicWebhooksNowpaymentsPaymentRoute,
  ApiPublicWebhooksNowpaymentsPayoutRoute:
    ApiPublicWebhooksNowpaymentsPayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
