/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPagamentoPaymentIdRouteImport } from './routes/_authenticated/pagamento.$paymentId'
import { Route as ApiPublicWebhooksPixRouteImport } from './routes/api/public/webhooks/pix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentoPaymentIdRoute =
  AuthenticatedPagamentoPaymentIdRouteImport.update({
    id: '/pagamento/$paymentId',
    path: '/pagamento/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksPixRoute = ApiPublicWebhooksPixRouteImport.update({
  id: '/api/public/webhooks/pix',
  path: '/api/public/webhooks/pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/pagamento/$paymentId': typeof AuthenticatedPagamentoPaymentIdRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/pagamento/$paymentId': typeof AuthenticatedPagamentoPaymentIdRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/pagamento/$paymentId': typeof AuthenticatedPagamentoPaymentIdRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/dashboard'
    | '/planos'
    | '/pagamento/$paymentId'
    | '/api/public/webhooks/pix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/dashboard'
    | '/planos'
    | '/pagamento/$paymentId'
    | '/api/public/webhooks/pix'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/_authenticated/dashboard'
    | '/_authenticated/planos'
    | '/_authenticated/pagamento/$paymentId'
    | '/api/public/webhooks/pix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  ApiPublicWebhooksPixRoute: typeof ApiPublicWebhooksPixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamento/$paymentId': {
      id: '/_authenticated/pagamento/$paymentId'
      path: '/pagamento/$paymentId'
      fullPath: '/pagamento/$paymentId'
      preLoaderRoute: typeof AuthenticatedPagamentoPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/pix': {
      id: '/api/public/webhooks/pix'
      path: '/api/public/webhooks/pix'
      fullPath: '/api/public/webhooks/pix'
      preLoaderRoute: typeof ApiPublicWebhooksPixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPagamentoPaymentIdRoute: typeof AuthenticatedPagamentoPaymentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPagamentoPaymentIdRoute: AuthenticatedPagamentoPaymentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  ApiPublicWebhooksPixRoute: ApiPublicWebhooksPixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
