/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhooksPixRouteImport } from './routes/api/public/webhooks/pix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPixRoute = ApiPublicWebhooksPixRouteImport.update({
  id: '/api/public/webhooks/pix',
  path: '/api/public/webhooks/pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/webhooks/pix'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/webhooks/pix'
  id: '__root__' | '/' | '/api/public/webhooks/pix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicWebhooksPixRoute: typeof ApiPublicWebhooksPixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/pix': {
      id: '/api/public/webhooks/pix'
      path: '/api/public/webhooks/pix'
      fullPath: '/api/public/webhooks/pix'
      preLoaderRoute: typeof ApiPublicWebhooksPixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicWebhooksPixRoute: ApiPublicWebhooksPixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
